### PR TITLE
New Version

### PR DESCRIPTION
**Pull request by dlaehnemann**
Sorry, no write access for me on the master branch--so I'll go through this branch and see how far I get.

### CODE REVIEW

**Comment by dlaehnemann** [comment]
Even though this passes, please wait until PR #23 is merged and this branch is rebased onto the new master. This way we avoid a little bug in the new version.

**Comment by johanneskoester** [comment]
Good catch!

**Comment by dlaehnemann** [comment]
Thanks, just created the release.

**Comment by dlaehnemann** [comment]
Anything that I can do to get the new version published on crates.io? Or does this somehow work automagically through webhooks, and all I need is patience?

**Comment by johanneskoester** [comment]
I think I have to do that (cargo publish). Give me a second.

**Comment by dlaehnemann** [comment]
Already available, thanks a bunch!

Out of curiosity: Do you just run `cargo publish` locally on your machine on the latest master commit?

**Comment by johanneskoester** [comment]
Exactly.

**Pull request merged**
